// frontend/src/app/search/search-results/search-results.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: "search-results-component",
  templateUrl: "./search-results.component.html"
})
export class SearchResultsComponent {
  @Input() searchResults = {};
}

<div>
  <div>
    <li *ngFor="let document of searchResults">
      {{ document.SupplierName }} {{ document.InvoiceNumber }}
    </li>
  </div>
</div>

// react-frontend/src/SearchResults/SearchResults.js
import React from "react";

export function SearchResultsComponent(props) {
  if (props.documents.length === 0) {
    return "No search results";
  }

  const resultRow = props.documents.map(r => (
    <li key={r.Id}>
      {r.InvoiceNumber}, {r.SupplierName}
    </li>
  ));

  return <div>{resultRow}</div>;
}
