// react-frontend/src/SearchForm/SearchForm.js
import React, { useState } from "react";
import { performSearch } from "./SearchService";

export function SearchFormComponent(props) {
  const [searchText, setSearchText] = useState("");

  const handleInput = event => {
    setSearchText(event.target.value);
  };

  function handleSearch() {
    performSearch(searchText)
      .then(res => {
        props.onSearchPerformed(res);
      })
      .catch(error => console.log(error));
  }

  return (
    <div>
      <input onBlur={handleInput} placeholder="Input search text" />
      <button onClick={handleSearch}>Search</button>
    </div>
  );
}

// frontend/src/app/search/search-form/search-form.component.ts
import { Component, EventEmitter, Output } from "@angular/core";
import { HttpClient } from "@angular/common/http";
import { Observable } from "rxjs";
import { SearchFormService } from "./search-form.service";

@Component({
  selector: "search-form-component",
  templateUrl: "./search-form.component.html",
  styleUrls: ["./search-form.component.css"]
})
export class SearchFormComponent {
  searchText = "";
  @Output() searched = new EventEmitter<{}>();

  constructor(private searchFormService: SearchFormService) {}

  onBlur(searchText: string): void {
    this.searchText = searchText;
  }

  performSearch(): void {
    console.log(this.searchText);
    this.searchFormService
      .getDocuments(this.searchText)
      .subscribe(h => this.searched.emit(h));
  }
}

<div class="search">
  <div class="search-div">
    <input
      (blur)="onBlur($event.target.value)"
      placeholder="Input search text"
    />
    <button (click)="performSearch()">
      Search
    </button>
  </div>
</div>
